### ISSUE TITLE
Rename background image cause IDE to crash.

### ISSUE THREAD

**Issue by Verrickt** [buchizo/ClaudiaIDE#23]
Title says it.
Here's how to reproduce.
Say I have an image SomeImage.png.
1.Set SomeImage.png the background image at setting page of ClaudialIDE
2.Close Visual Studio.
3.Rename SomeImage.png to AnotherImage.png in FileExplorer
4.Open Visual Studio.
5.Visual Studio crashes when opening editor.

Guess the invalid path is the cause of the problem. Cause if you change background image to another valid one before trying open editor , it works just fine.

Here's the log from EventViewer

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Media.Imaging.BitmapInitialize.EnsureInitializedComplete()
   at System.Windows.Media.Imaging.BitmapSource.get_Format()
   at System.Windows.Media.Imaging.BitmapSource.get_DUCECompatiblePtr()
   at System.Windows.Media.Imaging.BitmapSource.UpdateBitmapSourceResource(Channel, Boolean)
   at System.Windows.Media.Imaging.BitmapSource.UpdateResource(Channel, Boolean)
   at System.Windows.Media.Imaging.BitmapSource.AddRefOnChannelCore(Channel)
   at System.Windows.Media.Imaging.BitmapSource.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel)
   at System.Windows.Media.ImageBrush.AddRefOnChannelCore(Channel)
   at System.Windows.Media.Brush.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel)
   at System.Windows.Media.RenderData.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel)
   at System.Windows.UIElement.RenderContent(System.Windows.Media.RenderContext, Boolean)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.UpdateChildren(System.Windows.Media.RenderContext, ResourceHandle)
   at System.Windows.Media.Visual.RenderRecursive(System.Windows.Media.RenderContext)
   at System.Windows.Media.Visual.Render(System.Windows.Media.RenderContext, UInt32)
   at System.Windows.Media.CompositionTarget.Compile(Channel)
   at System.Windows.Media.CompositionTarget.System.Windows.Media.ICompositionTarget.Render(Boolean, Channel)
   at System.Windows.Media.MediaContext.Render(System.Windows.Media.ICompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Media.MediaContext.Resize(System.Windows.Media.ICompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)


```

**Comment by buchizo** [comment]
@Verrickt , Thank you for your report. I'd like to fix this.
